<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use App\Models\Tenant;
use App\Models\Dealer;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tenant = Tenant::first();
        $dealer = Dealer::first();
        
        if (!$tenant) {
            $this->command->error('No tenants found! Run TenantSeeder first.');
            return;
        }

        $vehicles = [
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024001',
                'stock_number' => 'TC001',
                'make' => 'Toyota',
                'model' => 'Camry',
                'sub_model' => 'XLE',
                'vehicle_type' => 'Sedan',
                'year' => 2023,
                'color' => 'Silver',
                'country_of_origin' => 'Japan',
                'fuel_type' => 'Gasoline',
                'mileage' => 15000,
                'transmission_type' => 'Automatic',
                'engine_size' => '2.5L',
                'vin' => '4T1B11HK5KU123456',
                'registration_type' => 'Registered',
                'price' => 28999.99,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Well-maintained Toyota Camry with low mileage. Perfect for daily commute.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024002',
                'stock_number' => 'HC002',
                'make' => 'Honda',
                'model' => 'Civic',
                'sub_model' => 'Sport',
                'vehicle_type' => 'Sedan',
                'year' => 2022,
                'color' => 'Blue',
                'country_of_origin' => 'Japan',
                'fuel_type' => 'Gasoline',
                'mileage' => 22000,
                'transmission_type' => 'CVT',
                'engine_size' => '2.0L',
                'vin' => '2HGFC2F59NH123456',
                'registration_type' => 'Registered',
                'price' => 24500.00,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Honda Civic Sport with sporty design and excellent fuel economy.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024003',
                'stock_number' => 'BM003',
                'make' => 'BMW',
                'model' => '3 Series',
                'sub_model' => '330i',
                'vehicle_type' => 'Sedan',
                'year' => 2021,
                'color' => 'Black',
                'country_of_origin' => 'Germany',
                'fuel_type' => 'Gasoline',
                'mileage' => 35000,
                'transmission_type' => 'Automatic',
                'engine_size' => '2.0L Turbo',
                'vin' => 'WBA5A5C50JB123456',
                'registration_type' => 'Registered',
                'price' => 35999.99,
                'dealer_id' => $dealer?->id,
                'status' => 'Reserved',
                'description' => 'Luxury BMW 3 Series with premium features and performance.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024004',
                'stock_number' => 'MB004',
                'make' => 'Mercedes-Benz',
                'model' => 'C-Class',
                'sub_model' => 'C300',
                'vehicle_type' => 'Sedan',
                'year' => 2020,
                'color' => 'White',
                'country_of_origin' => 'Germany',
                'fuel_type' => 'Gasoline',
                'mileage' => 45000,
                'transmission_type' => 'Automatic',
                'engine_size' => '2.0L Turbo',
                'vin' => '55SWF4KB3LU123456',
                'registration_type' => 'Registered',
                'price' => 38500.00,
                'dealer_id' => $dealer?->id,
                'status' => 'Sold',
                'description' => 'Elegant Mercedes-Benz C-Class with luxury interior.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024005',
                'stock_number' => 'TS005',
                'make' => 'Tesla',
                'model' => 'Model 3',
                'sub_model' => 'Long Range',
                'vehicle_type' => 'Sedan',
                'year' => 2024,
                'color' => 'Red',
                'country_of_origin' => 'USA',
                'fuel_type' => 'Electric',
                'mileage' => 5000,
                'transmission_type' => 'Automatic',
                'engine_size' => 'Electric Motor',
                'vin' => '5YJ3E1EB5NF123456',
                'registration_type' => 'Registered',
                'price' => 49999.99,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Brand new Tesla Model 3 with autopilot and long range battery.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024006',
                'stock_number' => 'FD006',
                'make' => 'Ford',
                'model' => 'F-150',
                'sub_model' => 'Lariat',
                'vehicle_type' => 'Pickup',
                'year' => 2023,
                'color' => 'Gray',
                'country_of_origin' => 'USA',
                'fuel_type' => 'Gasoline',
                'mileage' => 12000,
                'transmission_type' => 'Automatic',
                'engine_size' => '3.5L V6',
                'vin' => '1FTEW1EP5PFC12345',
                'registration_type' => 'Registered',
                'price' => 52000.00,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Powerful Ford F-150 pickup truck with towing capacity.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024007',
                'stock_number' => 'AU007',
                'make' => 'Audi',
                'model' => 'Q5',
                'sub_model' => 'Premium Plus',
                'vehicle_type' => 'SUV',
                'year' => 2022,
                'color' => 'Black',
                'country_of_origin' => 'Germany',
                'fuel_type' => 'Gasoline',
                'mileage' => 28000,
                'transmission_type' => 'Automatic',
                'engine_size' => '2.0L Turbo',
                'vin' => 'WA1BVAFY8N2123456',
                'registration_type' => 'Registered',
                'price' => 42500.00,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Luxury Audi Q5 SUV with Quattro all-wheel drive.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024008',
                'stock_number' => 'HY008',
                'make' => 'Hyundai',
                'model' => 'Tucson',
                'sub_model' => 'SEL',
                'vehicle_type' => 'SUV',
                'year' => 2023,
                'color' => 'Blue',
                'country_of_origin' => 'South Korea',
                'fuel_type' => 'Hybrid',
                'mileage' => 8000,
                'transmission_type' => 'Automatic',
                'engine_size' => '1.6L Turbo',
                'vin' => 'KM8J3CAL5PU123456',
                'registration_type' => 'Registered',
                'price' => 32000.00,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Fuel-efficient Hyundai Tucson Hybrid with modern features.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024009',
                'stock_number' => 'MZ009',
                'make' => 'Mazda',
                'model' => 'CX-5',
                'sub_model' => 'Touring',
                'vehicle_type' => 'SUV',
                'year' => 2021,
                'color' => 'Red',
                'country_of_origin' => 'Japan',
                'fuel_type' => 'Gasoline',
                'mileage' => 38000,
                'transmission_type' => 'Automatic',
                'engine_size' => '2.5L',
                'vin' => 'JM3KFBCM5M0123456',
                'registration_type' => 'Registered',
                'price' => 27500.00,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Stylish Mazda CX-5 with excellent handling and comfort.',
            ],
            [
                'tenant_id' => $tenant->id,
                'vehicle_code' => 'VH2024010',
                'stock_number' => 'CV010',
                'make' => 'Chevrolet',
                'model' => 'Silverado',
                'sub_model' => 'LT',
                'vehicle_type' => 'Pickup',
                'year' => 2022,
                'color' => 'White',
                'country_of_origin' => 'USA',
                'fuel_type' => 'Diesel',
                'mileage' => 25000,
                'transmission_type' => 'Automatic',
                'engine_size' => '3.0L Turbo Diesel',
                'vin' => '1GCUYCE07NZ123456',
                'registration_type' => 'Registered',
                'price' => 48000.00,
                'dealer_id' => $dealer?->id,
                'status' => 'Available',
                'description' => 'Heavy-duty Chevrolet Silverado with diesel engine.',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::firstOrCreate(
                ['vehicle_code' => $vehicle['vehicle_code']],
                $vehicle
            );
            // Ensure stock_number is back-filled for existing rows that lack it
            Vehicle::where('vehicle_code', $vehicle['vehicle_code'])
                ->whereNull('stock_number')
                ->update(['stock_number' => $vehicle['stock_number']]);
        }

        $this->command->info('Vehicles seeded successfully! Created ' . count($vehicles) . ' vehicles.');
    }
}
